In [1]:
import numpy as np
import pandas as pd

In [2]:
file_path = "D:\\VNSGU_PDA_DATA\\Data-Analytics-using-Python-Minor-Project\\Data\\raw\\VNSGU_Results.xlsx"
df = pd.read_excel(file_path)

In [3]:
df.head(5)

,Seat Number,Name,College Name,Total Marks,SGPA,Result,Course_Name,ADVANCE_WEB_TECHNOLOGY_Ext_Theory,ADVANCE_WEB_TECHNOLOGY_Ext_Practical,ADVANCE_WEB_TECHNOLOGY_Total_Ext,...,NETWORK_TECHNOLOGY_Int_Practical,NETWORK_TECHNOLOGY_Total_Int,NETWORK_TECHNOLOGY_Total_Obt,Course_Ext_Theory,Course_Ext_Practical,Course_Total_Ext,Course_Int_Theory,Course_Int_Practical,Course_Total_Int,Course_Total_Obt
0,1001,ADEP SAIKRISHNA KISHORBHAI,"V.S. PATEL COLLEGE OF ARTS & SCIENCE, BILIMORA",332 / 550,6.18,PASS,CERTIFICATE COURSE ON GOOGLE PRODUCTS(CCGP),11.0,22.0,33.0,...,0,36.0,56.0,0,0,15.0,0,0,17,32.0
1,1002,AHIR KRISH PRAMODKUMAR,"V.S. PATEL COLLEGE OF ARTS & SCIENCE, BILIMORA",347 / 550,6.36,PASS,CERTIFICATE COURSE ON GOOGLE PRODUCTS(CCGP),9.0,19.0,28.0,...,0,38.0,66.0,0,0,25.0,0,0,15,40.0
2,1003,AHIR MEET MANSUKHBHAI,"V.S. PATEL COLLEGE OF ARTS & SCIENCE, BILIMORA",348 / 550,6.18,PASS,CERTIFICATE COURSE ON GOOGLE PRODUCTS(CCGP),16.0,19.0,35.0,...,0,40.0,65.0,0,0,17.0,0,0,12,29.0
3,1004,AHIR MITKUMAR SURESHBHAI,"V.S. PATEL COLLEGE OF ARTS & SCIENCE, BILIMORA",347 / 550,6.36,PASS,CERTIFICATE COURSE ON GOOGLE PRODUCTS(CCGP),12.0,19.0,31.0,...,0,30.0,56.0,0,0,25.0,0,0,14,39.0
4,1005,AHIR NILAY ARVINDBHAI,"V.S. PATEL COLLEGE OF ARTS & SCIENCE, BILIMORA",325 / 550,5.82,PASS,CERTIFICATE COURSE ON GOOGLE PRODUCTS(CCGP),13.0,19.0,32.0,...,0,33.0,53.0,0,0,20.0,0,0,11,31.0

In [4]:
df.shape

(8987, 49)

In [5]:
df.columns

Index(['Seat Number', 'Name', 'College Name', 'Total Marks', 'SGPA', 'Result',
       'Course_Name', 'ADVANCE_WEB_TECHNOLOGY_Ext_Theory',
       'ADVANCE_WEB_TECHNOLOGY_Ext_Practical',
       'ADVANCE_WEB_TECHNOLOGY_Total_Ext', 'ADVANCE_WEB_TECHNOLOGY_Int_Theory',
       'ADVANCE_WEB_TECHNOLOGY_Int_Practical',
       'ADVANCE_WEB_TECHNOLOGY_Total_Int', 'ADVANCE_WEB_TECHNOLOGY_Total_Obt',
       'WEB_FRAMEWORK_AND_SERVICES_Ext_Theory',
       'WEB_FRAMEWORK_AND_SERVICES_Ext_Practical',
       'WEB_FRAMEWORK_AND_SERVICES_Total_Ext',
       'WEB_FRAMEWORK_AND_SERVICES_Int_Theory',
       'WEB_FRAMEWORK_AND_SERVICES_Int_Practical',
       'WEB_FRAMEWORK_AND_SERVICES_Total_Int',
       'WEB_FRAMEWORK_AND_SERVICES_Total_Obt', '.NET_TECHNOLOGY_Ext_Theory',
       '.NET_TECHNOLOGY_Ext_Practical', '.NET_TECHNOLOGY_Total_Ext',
       '.NET_TECHNOLOGY_Int_Theory', '.NET_TECHNOLOGY_Int_Practical',
       '.NET_TECHNOLOGY_Total_Int', '.NET_TECHNOLOGY_Total_Obt',
       'LINUX_OPERATING_SYSTEM(LOS)_Ext_Theory',
       'LINUX_OPERATING_SYSTEM(LOS)_Ext_Practical',
       'LINUX_OPERATING_SYSTEM(LOS)_Total_Ext',
       'LINUX_OPERATING_SYSTEM(LOS)_Int_Theory',
       'LINUX_OPERATING_SYSTEM(LOS)_Int_Practical',
       'LINUX_OPERATING_SYSTEM(LOS)_Total_Int',
       'LINUX_OPERATING_SYSTEM(LOS)_Total_Obt',
       'NETWORK_TECHNOLOGY_Ext_Theory', 'NETWORK_TECHNOLOGY_Ext_Practical',
       'NETWORK_TECHNOLOGY_Total_Ext', 'NETWORK_TECHNOLOGY_Int_Theory',
       'NETWORK_TECHNOLOGY_Int_Practical', 'NETWORK_TECHNOLOGY_Total_Int',
       'NETWORK_TECHNOLOGY_Total_Obt', 'Course_Ext_Theory',
       'Course_Ext_Practical', 'Course_Total_Ext', 'Course_Int_Theory',
       'Course_Int_Practical', 'Course_Total_Int', 'Course_Total_Obt'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8987 entries, 0 to 8986
Data columns (total 49 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Seat Number                                8987 non-null   int64
 1   Name                                       8987 non-null   object
 2   College Name                               8987 non-null   object
 3   Total Marks                                8987 non-null   object
 4   SGPA                                       8987 non-null   object
 5   Result                                     8987 non-null   object
 6   Course_Name                                8987 non-null   object
 7   ADVANCE_WEB_TECHNOLOGY_Ext_Theory          8950 non-null   float64
 8   ADVANCE_WEB_TECHNOLOGY_Ext_Practical       8805 non-null   float64
 9   ADVANCE_WEB_TECHNOLOGY_Total_Ext           8793 non-null   float64
 10  ADVANCE_WEB_TECHNOLOGY_Int_Theory          8987 non-null   int64
 11  ADVANCE_WEB_TECHNOLOGY_Int_Practical       8942 non-null   float64
 12  ADVANCE_WEB_TECHNOLOGY_Total_Int           8942 non-null   float64
 13  ADVANCE_WEB_TECHNOLOGY_Total_Obt           8987 non-null   int64
 14  WEB_FRAMEWORK_AND_SERVICES_Ext_Theory      8948 non-null   float64
 15  WEB_FRAMEWORK_AND_SERVICES_Ext_Practical   8830 non-null   float64
 16  WEB_FRAMEWORK_AND_SERVICES_Total_Ext       8819 non-null   float64
 17  WEB_FRAMEWORK_AND_SERVICES_Int_Theory      8986 non-null   float64
 18  WEB_FRAMEWORK_AND_SERVICES_Int_Practical   8940 non-null   float64
 19  WEB_FRAMEWORK_AND_SERVICES_Total_Int       8940 non-null   float64
 20  WEB_FRAMEWORK_AND_SERVICES_Total_Obt       8986 non-null   float64
 21  .NET_TECHNOLOGY_Ext_Theory                 8948 non-null   float64
 22  .NET_TECHNOLOGY_Ext_Practical              8884 non-null   float64
 23  .NET_TECHNOLOGY_Total_Ext                  8874 non-null   float64
 24  .NET_TECHNOLOGY_Int_Theory                 8986 non-null   float64
 25  .NET_TECHNOLOGY_Int_Practical              8976 non-null   float64
 26  .NET_TECHNOLOGY_Total_Int                  8976 non-null   float64
 27  .NET_TECHNOLOGY_Total_Obt                  8986 non-null   float64
 28  LINUX_OPERATING_SYSTEM(LOS)_Ext_Theory     8944 non-null   float64
 29  LINUX_OPERATING_SYSTEM(LOS)_Ext_Practical  8882 non-null   float64
 30  LINUX_OPERATING_SYSTEM(LOS)_Total_Ext      8870 non-null   float64
 31  LINUX_OPERATING_SYSTEM(LOS)_Int_Theory     8986 non-null   float64
 32  LINUX_OPERATING_SYSTEM(LOS)_Int_Practical  8979 non-null   float64
 33  LINUX_OPERATING_SYSTEM(LOS)_Total_Int      8978 non-null   float64
 34  LINUX_OPERATING_SYSTEM(LOS)_Total_Obt      8978 non-null   float64
 35  NETWORK_TECHNOLOGY_Ext_Theory              8987 non-null   int64
 36  NETWORK_TECHNOLOGY_Ext_Practical           8987 non-null   int64
 37  NETWORK_TECHNOLOGY_Total_Ext               8653 non-null   float64
 38  NETWORK_TECHNOLOGY_Int_Theory              8987 non-null   int64
 39  NETWORK_TECHNOLOGY_Int_Practical           8987 non-null   int64
 40  NETWORK_TECHNOLOGY_Total_Int               8986 non-null   float64
 41  NETWORK_TECHNOLOGY_Total_Obt               8938 non-null   float64
 42  Course_Ext_Theory                          8987 non-null   int64
 43  Course_Ext_Practical                       8987 non-null   int64
 44  Course_Total_Ext                           8956 non-null   float64
 45  Course_Int_Theory                          8987 non-null   int64
 46  Course_Int_Practical                       8987 non-null   int64
 47  Course_Total_Int                           8987 non-null   int64
 48  Course_Total_Obt                           8986 non-null   float64
dtypes: float64(31), int64(12), object(6)
memory usage: 3.4+ MB

In [7]:
df.describe()

,Seat Number,ADVANCE_WEB_TECHNOLOGY_Ext_Theory,ADVANCE_WEB_TECHNOLOGY_Ext_Practical,ADVANCE_WEB_TECHNOLOGY_Total_Ext,ADVANCE_WEB_TECHNOLOGY_Int_Theory,ADVANCE_WEB_TECHNOLOGY_Int_Practical,ADVANCE_WEB_TECHNOLOGY_Total_Int,ADVANCE_WEB_TECHNOLOGY_Total_Obt,WEB_FRAMEWORK_AND_SERVICES_Ext_Theory,WEB_FRAMEWORK_AND_SERVICES_Ext_Practical,...,NETWORK_TECHNOLOGY_Int_Practical,NETWORK_TECHNOLOGY_Total_Int,NETWORK_TECHNOLOGY_Total_Obt,Course_Ext_Theory,Course_Ext_Practical,Course_Total_Ext,Course_Int_Theory,Course_Int_Practical,Course_Total_Int,Course_Total_Obt
count,8987.000000,8950.000000,8805.000000,8793.000000,8987.000000,8942.000000,8942.000000,8987.000000,8948.000000,8830.000000,...,8987.0,8986.000000,8938.000000,8987.0,8987.0,8956.000000,8987.0,8987.0,8987.000000,8986.000000
mean,5520.181262,12.612514,18.125951,30.813261,17.628463,19.949117,37.603556,67.823968,13.344323,18.250057,...,0.0,35.912531,64.837324,0.0,0.0,19.973872,0.0,0.0,20.071882,39.987091
std,2609.081077,4.584711,3.420402,6.516300,3.600709,3.468778,5.958057,11.734305,4.612686,3.169073,...,0.0,6.788770,13.035321,0.0,0.0,3.942749,0.0,0.0,3.248098,6.356489
min,1001.000000,1.000000,5.000000,9.000000,5.000000,8.000000,16.000000,9.000000,1.000000,5.000000,...,0.0,9.000000,18.000000,0.0,0.0,3.000000,0.0,0.0,6.000000,14.000000
25%,3264.500000,9.000000,16.000000,26.000000,15.000000,18.000000,34.000000,60.000000,10.000000,16.000000,...,0.0,32.000000,56.000000,0.0,0.0,18.000000,0.0,0.0,18.000000,36.000000
50%,5513.000000,13.000000,18.000000,31.000000,18.000000,20.000000,38.000000,68.000000,13.000000,18.000000,...,0.0,37.000000,66.000000,0.0,0.0,21.000000,0.0,0.0,20.000000,41.000000
75%,7771.500000,16.000000,21.000000,35.000000,20.000000,23.000000,42.000000,76.000000,17.000000,20.000000,...,0.0,41.000000,74.000000,0.0,0.0,23.000000,0.0,0.0,23.000000,45.000000
max,10042.000000,25.000000,25.000000,49.000000,25.000000,25.000000,50.000000,99.000000,25.000000,25.000000,...,0.0,50.000000,98.000000,0.0,0.0,25.000000,0.0,0.0,25.000000,50.000000

In [8]:
df.isnull().sum()

Seat Number                                    0
Name                                           0
College Name                                   0
Total Marks                                    0
SGPA                                           0
Result                                         0
Course_Name                                    0
ADVANCE_WEB_TECHNOLOGY_Ext_Theory             37
ADVANCE_WEB_TECHNOLOGY_Ext_Practical         182
ADVANCE_WEB_TECHNOLOGY_Total_Ext             194
ADVANCE_WEB_TECHNOLOGY_Int_Theory              0
ADVANCE_WEB_TECHNOLOGY_Int_Practical          45
ADVANCE_WEB_TECHNOLOGY_Total_Int              45
ADVANCE_WEB_TECHNOLOGY_Total_Obt               0
WEB_FRAMEWORK_AND_SERVICES_Ext_Theory         39
WEB_FRAMEWORK_AND_SERVICES_Ext_Practical     157
WEB_FRAMEWORK_AND_SERVICES_Total_Ext         168
WEB_FRAMEWORK_AND_SERVICES_Int_Theory          1
WEB_FRAMEWORK_AND_SERVICES_Int_Practical      47
WEB_FRAMEWORK_AND_SERVICES_Total_Int          47
WEB_FRAMEWORK_AND_SERVICES_Total_Obt           1
.NET_TECHNOLOGY_Ext_Theory                    39
.NET_TECHNOLOGY_Ext_Practical                103
.NET_TECHNOLOGY_Total_Ext                    113
.NET_TECHNOLOGY_Int_Theory                     1
.NET_TECHNOLOGY_Int_Practical                 11
.NET_TECHNOLOGY_Total_Int                     11
.NET_TECHNOLOGY_Total_Obt                      1
LINUX_OPERATING_SYSTEM(LOS)_Ext_Theory        43
LINUX_OPERATING_SYSTEM(LOS)_Ext_Practical    105
LINUX_OPERATING_SYSTEM(LOS)_Total_Ext        117
LINUX_OPERATING_SYSTEM(LOS)_Int_Theory         1
LINUX_OPERATING_SYSTEM(LOS)_Int_Practical      8
LINUX_OPERATING_SYSTEM(LOS)_Total_Int          9
LINUX_OPERATING_SYSTEM(LOS)_Total_Obt          9
NETWORK_TECHNOLOGY_Ext_Theory                  0
NETWORK_TECHNOLOGY_Ext_Practical               0
NETWORK_TECHNOLOGY_Total_Ext                 334
NETWORK_TECHNOLOGY_Int_Theory                  0
NETWORK_TECHNOLOGY_Int_Practical               0
NETWORK_TECHNOLOGY_Total_Int                   1
NETWORK_TECHNOLOGY_Total_Obt                  49
Course_Ext_Theory                              0
Course_Ext_Practical                           0
Course_Total_Ext                              31
Course_Int_Theory                              0
Course_Int_Practical                           0
Course_Total_Int                               0
Course_Total_Obt                               1
dtype: int64